import type { Trip } from "./types";

export const initialTrip: Trip = {
  id: "couple-trip-main",
  title: "Escapada a Roma",
  destination: "Roma, Italia",
  startDate: "2026-09-10",
  endDate: "2026-09-14",
  currency: "EUR",
  days: [
    {
      id: "day-1",
      date: "2026-09-10",
      title: "Llegada tranquila",
      city: "Roma",
      notes: "Check-in, paseo suave y cena sin prisas.",
      routeStopIds: ["hotel-artemide", "fontana-trevi", "trastevere-dinner"],
    },
    {
      id: "day-2",
      date: "2026-09-11",
      title: "Roma clásica",
      city: "Roma",
      notes: "Comprar entradas con hora para evitar colas.",
      routeStopIds: ["colosseum", "forum", "pantheon"],
    },
    {
      id: "day-3",
      date: "2026-09-12",
      title: "Vaticano y atardecer",
      city: "Roma",
      notes: "Día más largo: reservar hueco para descansar.",
      routeStopIds: ["vatican", "castel-santangelo", "pincio"],
    },
  ],
  places: [
    {
      id: "hotel-artemide",
      name: "Hotel Artemide",
      category: "hotel",
      status: "booked",
      address: "Via Nazionale 22, Roma",
      lat: 41.9006,
      lng: 12.4937,
      dayId: "day-1",
      notes: "Base posible cerca de Termini y del centro.",
      estimatedCost: 420,
      tags: ["hotel", "base"],
    },
    {
      id: "fontana-trevi",
      name: "Fontana di Trevi",
      category: "monument",
      status: "planned",
      address: "Piazza di Trevi, Roma",
      lat: 41.9009,
      lng: 12.4833,
      dayId: "day-1",
      notes: "Ir de noche si está muy llena.",
      estimatedCost: 0,
      tags: ["paseo", "foto"],
    },
    {
      id: "trastevere-dinner",
      name: "Cena en Trastevere",
      category: "restaurant",
      status: "idea",
      address: "Trastevere, Roma",
      lat: 41.8894,
      lng: 12.4663,
      dayId: "day-1",
      notes: "Buscar trattoria pequeña y reservar terraza.",
      estimatedCost: 70,
      tags: ["cena", "romántico"],
    },
    {
      id: "colosseum",
      name: "Coliseo",
      category: "monument",
      status: "planned",
      address: "Piazza del Colosseo, Roma",
      lat: 41.8902,
      lng: 12.4922,
      dayId: "day-2",
      notes: "Entrada combinada Coliseo + Foro.",
      estimatedCost: 36,
      tags: ["historia"],
    },
    {
      id: "forum",
      name: "Foro Romano",
      category: "monument",
      status: "planned",
      address: "Via della Salara Vecchia, Roma",
      lat: 41.8925,
      lng: 12.4853,
      dayId: "day-2",
      notes: "Llevar agua y gorra.",
      estimatedCost: 0,
      tags: ["historia", "paseo"],
    },
    {
      id: "pantheon",
      name: "Panteón",
      category: "monument",
      status: "booked",
      address: "Piazza della Rotonda, Roma",
      lat: 41.8986,
      lng: 12.4769,
      dayId: "day-2",
      notes: "Entrada económica, revisar horario.",
      estimatedCost: 10,
      tags: ["historia"],
    },
    {
      id: "vatican",
      name: "Museos Vaticanos",
      category: "monument",
      status: "idea",
      address: "Viale Vaticano, Roma",
      lat: 41.9065,
      lng: 12.4536,
      dayId: "day-3",
      notes: "Reservar temprano.",
      estimatedCost: 50,
      tags: ["arte", "reserva"],
    },
    {
      id: "castel-santangelo",
      name: "Castel Sant'Angelo",
      category: "monument",
      status: "idea",
      address: "Lungotevere Castello 50, Roma",
      lat: 41.9031,
      lng: 12.4663,
      dayId: "day-3",
      notes: "Bonitas vistas al río.",
      estimatedCost: 28,
      tags: ["vistas"],
    },
    {
      id: "pincio",
      name: "Terrazza del Pincio",
      category: "nature",
      status: "planned",
      address: "Salita del Pincio, Roma",
      lat: 41.9115,
      lng: 12.4763,
      dayId: "day-3",
      notes: "Atardecer si el tiempo acompaña.",
      estimatedCost: 0,
      tags: ["atardecer", "foto"],
    },
  ],
  reservations: [
    {
      id: "flight-out",
      type: "flight",
      title: "Vuelo Madrid - Roma",
      provider: "ITA Airways",
      date: "2026-09-10",
      time: "08:30",
      locator: "ABC123",
      amount: 240,
      status: "confirmed",
      notes: "Facturar una maleta compartida.",
      dayId: "day-1",
    },
    {
      id: "hotel-reservation",
      type: "hotel",
      title: "Hotel Artemide",
      provider: "Booking",
      date: "2026-09-10",
      time: "15:00",
      locator: "HTL-ROMA",
      amount: 420,
      status: "confirmed",
      notes: "Cancelación gratuita hasta una semana antes.",
      dayId: "day-1",
    },
  ],
  checklist: [
    { id: "dni", label: "DNI / pasaporte", done: true, group: "Documentos" },
    { id: "tarjeta", label: "Tarjeta sin comisiones", done: false, group: "Dinero" },
    { id: "seguro", label: "Seguro de viaje", done: false, group: "Documentos" },
    { id: "adaptador", label: "Adaptador y cargadores", done: true, group: "Maleta" },
    { id: "offline", label: "Mapas offline", done: false, group: "Móvil" },
  ],
  notes: [
    "Mirar restaurantes pequeños cerca de Trastevere.",
    "Dejar huecos libres para improvisar.",
  ],
};
